name: Test

on: [push]

jobs:
  test:
    stage: test  # Стадия тестирования
    variables:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"  # Переменная окружения для базы данных
    services:
      - name: postgres
        image: postgres:11  # Указываем сервис базы данных Postgres
    before_script:
      - pip install -r requirements.txt  # Устанавливаем зависимости перед запуском скриптов
      - python manage.py migrate  # Применяем миграции
    script:
      - pytest  # Запускаем тесты с использованием PyTest

  deploy:
    stage: deploy  # Стадия развертывания
    script:
      - docker build -t myproject .  # Собираем Docker-образ
      - docker-compose up -d  # Запускаем контейнеры в фоне

stages:
  - test
  - deploy
